// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwyabksynmxxsopsoilf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eWFia3N5bm14eHNvcHNvaWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjczOTEsImV4cCI6MjA2MTAwMzM5MX0.9yJaIALVaNVLXz4GbWnmuJ-aAOgBzD4xf4abXX6-4ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);